document.head.insertAdjacentHTML('beforeend','<style>.venue-grid.carousel{display:flex;gap:18px;overflow-x:auto;overflow-y:hidden;padding:0 1px 13px;scroll-snap-type:x mandatory;scrollbar-width:none}.venue-grid.carousel::-webkit-scrollbar{display:none}.venue-grid.carousel .venue{flex:0 0 calc((100% - 36px)/3);scroll-snap-align:start}.carousel-toolbar{display:flex;justify-content:flex-end;gap:8px;margin:-12px 0 16px}.carousel-control{display:grid;place-items:center;width:33px;height:33px;border-radius:50%;border:1px solid var(--line);background:#fff;color:var(--ink);font-size:17px;cursor:pointer}.carousel-control:hover{background:var(--lime);border-color:var(--lime)}@media(max-width:820px){.venue-grid.carousel .venue{flex-basis:calc((100% - 18px)/2)}}@media(max-width:540px){.venue-grid.carousel .venue{flex-basis:86%}.carousel-toolbar{margin-top:-4px}}</style>');
const venues=[
  ['Pavilion Kuala Lumpur','Bukit Bintang · 3 min walk','RM 8','12 spaces left'],['The Exchange TRX','Tun Razak Exchange · On-site','RM 10','8 spaces left'],['Suria KLCC','Kuala Lumpur City Centre · On-site','RM 9','21 spaces left'],['Mid Valley Megamall','Mid Valley City, Kuala Lumpur','RM 7','16 spaces left'],['1 Utama Shopping Centre','Bandar Utama, Selangor','RM 6','25 spaces left'],['Sunway Pyramid','Bandar Sunway, Selangor','RM 7','9 spaces left'],['IOI City Mall','Putrajaya','RM 5','32 spaces left'],['Paradigm Mall Petaling Jaya','Kelana Jaya, Selangor','RM 6','14 spaces left'],['AEON Mall Shah Alam','Seksyen 13, Shah Alam','RM 4','18 spaces left'],['Queensbay Mall','Bayan Lepas, Penang','RM 5','11 spaces left'],['Gurney Plaza','George Town, Penang','RM 6','7 spaces left'],['Gurney Paragon','George Town, Penang','RM 6','10 spaces left'],['Johor Bahru City Square','Johor Bahru, Johor','RM 5','19 spaces left'],['The Mall, Mid Valley Southkey','Johor Bahru, Johor','RM 5','13 spaces left'],['Imago Shopping Mall','Kota Kinabalu, Sabah','RM 5','15 spaces left'],['Suria Sabah','Kota Kinabalu, Sabah','RM 4','20 spaces left'],['1Borneo Hypermall','Kota Kinabalu, Sabah','RM 4','17 spaces left'],['The Spring Shopping Mall','Kuching, Sarawak','RM 4','14 spaces left'],['Vivacity Megamall','Kuching, Sarawak','RM 5','22 spaces left'],['CityONE Megamall','Kuching, Sarawak','RM 4','18 spaces left'],['Bintang Megamall','Miri, Sarawak','RM 4','11 spaces left']
].map(([name,area,price,spots])=>({name,area,price,spots}));
const destination=document.querySelector('#destination');venues.slice(14).forEach(v=>destination.insertAdjacentHTML('beforeend',`<option value="${v.name}">${v.name}</option>`));
const grid=document.querySelector('#venueGrid');grid.classList.add('carousel');grid.insertAdjacentHTML('beforebegin','<div class="carousel-toolbar"><button class="carousel-control" id="carouselPrev" aria-label="Previous malls">←</button><button class="carousel-control" id="carouselNext" aria-label="More malls">→</button></div>');
grid.innerHTML=venues.map(v=>`<article class="venue"><div class="venue-art" data-mall-image="${v.name}"><span class="tag">${v.spots}</span></div><div class="venue-info"><div class="venue-title"><h3>${v.name}</h3><span>↗</span></div><p>${v.area}</p><div class="venue-footer"><strong>${v.price} <small>/ hour</small></strong><a class="book-btn" href="spaces.html?venue=${encodeURIComponent(v.name)}&from=home-venues">Reserve spot</a></div></div></article>`).join('');
MallImages.apply(grid);const slide=direction=>grid.scrollBy({left:direction*grid.querySelector('.venue').getBoundingClientRect().width*1.08,behavior:'smooth'});document.querySelector('#carouselPrev').addEventListener('click',()=>slide(-1));document.querySelector('#carouselNext').addEventListener('click',()=>slide(1));
const date=document.querySelector('#arrival'),now=new Date();date.value=now.toISOString().slice(0,10);date.min=date.value;document.querySelector('#time').value=String(now.getHours()+1).padStart(2,'0')+':00';
document.querySelector('#searchForm').addEventListener('submit',event=>{event.preventDefault();location.href=`spaces.html?venue=${encodeURIComponent(destination.value)}&from=home-venues`});document.querySelector('#locate').addEventListener('click',()=>destination.focus());
